Get mutable references to the memory information
rust-osdev/multiboot2 pull request #140
Opened 2023-06-19 11:37 UTC by YtvwlD

This is (hopefully) the last part I split off of #133.

This PR adds the functions `basic_memory_info_tag_mut`, `memory_map_tag_mut` adn `efi_memory_map_tag_mut`. The memory map tags each get their own `memory_areas_mut`.

This may sound wrong at first and yes, this is really hacky, but I'm afraid that I need this.

The correct way to pass memory information from the bootloader to the kernel would be

1. gather memory information
2. build the appropriate tags
3. pass them into the builder
4. build the information struct

*But* steps 2 and 4 allocate memory which in turn might invalidate the gathered memory map.
One could either risk this and just pass possibly outdated information – or do it the other way round:

1. approximate how much memory areas there are
2. build the whole information struct
3. get the correct memory information
4. get the appropriate tags, mutably
5. put the information in there

(The downside to this approach is that there may be empty areas at the end (which seems to be fine) or that there are not enough areas.)

2023-06-19 11:47 UTC, phip1611 commented on multiboot2/src/lib.rs
> +            .map(|tag| unsafe { &mut *(tag as *mut Tag as *mut BasicMemoryInfoTag) })
I think `self.get_tag_mut(TagType::BasicMeminfo)` should be necessary?

2023-06-19 11:50 UTC, phip1611 commented on multiboot2/src/memory_map.rs
> +    #[cfg(feature = "builder")]
```suggestion
```

2023-06-19 11:53 UTC, phip1611 requested changes
fine with me. Users of this library could do this anyway with unsafe magic.. so just give them the necessary tools directly.


Please address the two open points. Otherwise, LGTM

2023-06-19 12:03 UTC, YtvwlD commented
Oh, yes, I missed that while rebasing.

2023-06-19 12:08 UTC, phip1611 approved these changes

2023-06-19 13:07 UTC, YtvwlD commented
Hm, I'm talking about UEFI and the default allocator: When I create boxes for the tags, they'll get put somewhere on the heap. This might be inside an existing memory region or it might allocate a new `LOADER_DATA` region.

The legacy map is only really accurate after calling `ExitBootServices`, I fear (after which the allocator doesn't work anymore).

Doing static allocations might work, but I'm not quite fond of that.

2023-06-20 09:38 UTC, phip1611 commented
```rust
// SAFETY: BootInformation contains a const ptr to memory that is never mutated.
// Sending this pointer to other threads is sound.
unsafe impl Send for BootInformation {}
```

If we merge this, this needs to be removed. Another breaking change. I think this could be okay, as one can wrap the MBI in a (custom) Mutex..

2023-06-20 13:03 UTC, YtvwlD commented
Huh, I don't know? The struct does need to be mutable for these methods to be called, but I'm not sure that's enough.

2023-06-21 15:06 UTC, phip1611 commented
I'm going to postpone this a bit and merge a few other things first. The rebase needed here will have a few conflicts - I'm sorry for that!

2023-06-26 07:28 UTC, YtvwlD commented
Sure, just ping me when I should rebase.

2023-06-26 09:23 UTC, YtvwlD commented
So, this should work (brb, testing this), but it really moves the `mut` through the whole codebase and I'm not happy about it.

2023-06-26 10:46 UTC, YtvwlD commented
I don't understand the miri failure, but this has better lifetimes and the integration test should work. I'm still not happy about having to touch so much code.

2023-07-03 08:35 UTC, YtvwlD commented
[Using `AsMut`](https://lab.whitequark.org/notes/2016-12-13/abstracting-over-mutability-in-rust/) might help with not-carrying-`mut`-through-the-whole-code, but I'm unsure whether this would look any better.

2023-07-09 10:48 UTC, YtvwlD commented
I think this looks better, though I'm not sure combining `EFIMemoryAreaIter` and `EFIMemoryAreaIterMut` is the way to go. (Combining `TagIter` and `TagIterMut` didn't work because there's pointers in them.)

2023-07-09 11:04 UTC, YtvwlD commented
That `unnecessary pub(self)` wasn't introduced by this pull request.

2023-07-14 13:42 UTC, YtvwlD commented
Oh, great!

(Don't mind me, this is just a rebase.)

2024-04-15 12:12 UTC, YtvwlD commented
(This is just a rebase.)

2024-04-26 16:53 UTC, YtvwlD commented
Yeah sure, take your time. I think this is the simplest change I can come up with right now, but if you find a simpler one, that'd be great.

2024-09-01 09:10 UTC, phip1611 commented
Sorry. I'm closing this due to massive internal refactorings, necessary for memory safety and removing any UB.

However, I think that the new design (based in `multiboot2-common`) can act as base to allow mutable 
references to multiboot2 structures

2024-09-01 09:10 UTC, closed without merging

2024-10-02 11:59 UTC, YtvwlD commented
Hm, I've been trying to port this over to the new design, but I'm currently stuck with quite a lot of duplications (`BytesRefMut`, `TagIterMut`, and about half of the functions in `DynSizedStructure`), so I'm not sure that this is the way to go.

2024-10-02 12:52 UTC, phip1611 commented
I think having additional `ByresRefMut` and `TagIterMut` is fine and necessary. The duplication is fine.

I'm not sure how `structDynSizedStructure` and `trait MaybeDynSized` need to be altered. Perhaps we also need a `trait MaybeDynSizedMut` trait.

2024-10-07 12:56 UTC, YtvwlD commented
Thanks for the input and pointing me to the diagrams! They make the two stages of parsing clearer, but I didn't fully grasp the last one, yet.

In any case, this seems to be a bit harder than I thought; mostly because `TagIterMut` doesn't seem to be straightforward, so I might take some time to get it right.

(In the mean time, what follows is a partial rebase; please ignore it. :)

2024-10-07 14:41 UTC, phip1611 commented
I'm sorry for the inconveniences. But all the refactorings were necessary to get rid of all UB.